services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: nine-kickoff-db
    environment:
      POSTGRES_USER: nineuser
      POSTGRES_PASSWORD: ninepass
      POSTGRES_DB: kickoff_challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nineuser -d kickoff_challenge"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for real-time features and caching
  redis:
    image: redis:7-alpine
    container_name: nine-kickoff-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer for database management (optional)
  adminer:
    image: adminer:4
    container_name: nine-kickoff-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
